name:                dot-xmonad
version:             0.1.0.0
github:              "wygulmage/xmonad"
license:             BSD3
author:              "keith"
maintainer:          "example@example.com"
copyright:           "2019 keith"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wygulmage/dot-xmonad#readme>

dependencies:
- base >= 4.7 && < 5

# library:
#   source-dirs: src

executables:
  xmonad:
    main:                xmonad.hs
    source-dirs:         .
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - xmonad
    - xmonad-contrib
    - X11
    - containers
    - xmobar
