resolver: lts-14.0

packages:
- .
- xmobar-git
- xmonad-git
- xmonad-contrib-git

extra-deps: 
    - iwlib-0.1.0
    - libmpd-0.9.0.10
flags: 
  xmobar:
    all_extensions: true
extra-package-dbs: []
