resolver: lts-20.16

packages:
- .
- xmobar-git
- xmonad-git
- xmonad-contrib-git

extra-deps: 
    # - iwlib-0.1.0
    - libmpd-0.10.0.0
    - netlink-1.1.1.0
    - X11-1.10

flags: 
  xmobar:
    all_extensions: true
extra-package-dbs: []

